<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Instrumental.ReadOnlyParameterAnalyzer</RootNamespace>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IsPackable>false</IsPackable>

    <!-- Avoid ID conflicts with the package project. -->
    <PackageId>*$(MSBuildProjectFile)*</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Instrumental.ReadOnlyParameterAnalyzer.BuildTime\Instrumental.ReadOnlyParameterAnalyzer.BuildTime.csproj" />
  </ItemGroup>

</Project>
